# GitHub workflow name
name: Build

# Build events
on:
  # Git push in master branch
  push:
    branches: [ master ]
  # Git pull request in master branch
  pull_request:
    branches: [ master ]
  # Manually triggered
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    # Build matrix (Linux, MacOS, Windows)
    strategy:
      fail-fast: false
      matrix:
        include:
        # Linux with gcc toolchain
        - name: "Linux (GCC)"
          os: ubuntu-latest
          toolchain: gcc
        # Linux with clang toolchain
        - name: "Linux (Clang)"
          os: ubuntu-latest
          toolchain: clang
        # MacOS with clang toolchain
        - name: "MacOS"
          os: macos-latest
          toolchain: clang 
        # Windows with Visual Studio toolchain
        - name: "Windows (Visual Studio)"
          os: windows-latest
          toolchain: msvc
        # Windows with MinGW toolchain
        - name: "Windows (MinGW)"
          os: windows-latest
          toolchain: mingw
        # Windows with Cygwin toolchain
        - name: "Windows (Cygwin)"
          os: windows-latest
          toolchain: cygwin

    steps:
      # git checkout
      - uses: actions/checkout@v2

      # cmake
      - name: "Display CMake version"
        run: cmake --version

      # gil
      - name: "Setup gil tool"
        run: |
#          pip3 install gil
#          gil update

      # Build step: Linux (GCC)
      - name: "Build step: Linux (GCC)"
#        if: startsWith(matrix.os, 'ubuntu') && matrix.toolchain == 'gcc'
        env:
          CC: gcc
          CXX: g++
        run: |
          echo ${{matrix.os}}
          echo ${{matrix.toolchain}}
#          cd build
#          ./unix.sh
