# GitHub workflow name
name: Build

# Build on push & pull request commands in master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    # Build matrix (Linux, MacOS, Windows)
    strategy:
      fail-fast: false
      matrix:
        config:
        - { 
            name: "Linux (GCC)"
            os: ubuntu-latest
            toolchain: "gcc" 
          }
        - { 
            name: "Linux (Clang)"
            os: ubuntu-latest
            toolchain: "clang"
          }
        - { 
            name: "MacOS"
            os: macos-latest
            toolchain: "clang" 
          }
        - { 
            name: "Windows (Visual Studio)"
            os: windows-latest
            toolchain: "msvc" 
          }
        - { 
            name: "Windows (MinGW)"
            os: windows-latest
            toolchain: "mingw" 
          }
        - { 
            name: "Windows (Cygwin)"
            os: windows-latest
            toolchain: "cygwin" 
          }

    name: ${ {matrix.config.name} }
    runs-on: ${ {matrix.config.os} }

    steps:
      - name: Display CMake version
        run: cmake --version
