# GitHub workflow name
name: Build

# Build events
on:
  # Git push in master branch
  push:
    branches: [ master ]
  # Git pull request in master branch
  pull_request:
    branches: [ master ]
  # Manually triggered
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    # Build matrix (Linux, MacOS, Windows)
    strategy:
      fail-fast: false
      matrix:
        config:
        - { 
            name: "Linux (GCC)",
            os: ubuntu-latest,
            toolchain: "gcc" 
          }
        - { 
            name: "Linux (Clang)",
            os: ubuntu-latest,
            toolchain: "clang"
          }
        - { 
            name: "MacOS",
            os: macos-latest,
            toolchain: "clang" 
          }
        - { 
            name: "Windows (Visual Studio)",
            os: windows-latest,
            toolchain: "msvc" 
          }
        - { 
            name: "Windows (MinGW)",
            os: windows-latest,
            toolchain: "mingw" 
          }
        - { 
            name: "Windows (Cygwin)",
            os: windows-latest,
            toolchain: "cygwin" 
          }

    steps:
      - name: Display CMake version
        run: cmake --version
