name: Windows (Cygwin)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Setup Cygwin"
        uses: egor-tensin/setup-cygwin@v3
        with:
          platform: x64
          packages: cmake gcc-g++

      - name: "Setup cmake"
        shell: C:\tools\cygwin\bin\bash -lc '{0}'
        run: cmake --version

      - name: "Setup gil tool"
        shell: C:\tools\cygwin\bin\bash -lc '{0}'
        run: |
          pip3 install gil
          gil update

      - name: "Build"
        shell: C:\tools\cygwin\bin\bash -lc '{0}'
        run: |
          cd build
          ./unix.sh
