name: Build Linux (GCC)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: "Linux (GCC)"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "Setup gcc"
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 11
          platform: x64

      - name: "Setup cmake"
        run: cmake --version

      - name: "Setup gil tool"
        run: |
          pip3 install gil
          gil update

      - name: "Build"
        run: |
          cd build
          ./unix.sh
