name: Windows (Visual Studio)

on:  [push]

jobs:
  build:
    runs-on: [self-hosted, windows-obiwan]
    steps:
      - uses: actions/checkout@v2

      - name: "Setup Visual Studio"
        uses: egor-tensin/vs-shell@v2

      - name: "Setup cmake"
        run: cmake --version

      - name: "Setup gil"
        run: |
          pip3 install gil
          gil update

      - name: "Build"
        run: |
          cd build
          ./vs.bat
