name: Doxygen

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Setup cmake"
        run: cmake --version

      - name: "Setup doxygen"
        run: |
          doxygen --version
          dot -V

      - name: "Setup gil tool"
        run: |
          pip3 install gil
          gil update

      - name: "Doxygen"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd build/Unix
          ./05-doxygen.sh
