name: Doxygen

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Setup cmake"
        run: cmake --version

      - name: "Setup doxygen"
        run: |
          sudo apt-get -y install doxygen graphviz
          doxygen --version
          dot -V

      - name: "Setup gil"
        run: |
          pip3 install gil
          gil update

      - name: "Setup git"
        run: |
          git config --global user.name "GitHub"
          git config --global user.email "github@github.com"
          git config --global push.default simple

      - name: "Doxygen"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ${GITHUB_TOKEN}
          cd build/Unix
          ./01-generate.sh
          ./05-doxygen.sh
